### 获取用户
GET http://localhost:8080/users

### 新增用户
POST http://localhost:8080/users
Content-Type: application/json

{"name":"张三","email":"zhangsan@example.com"}
# {"name":"李四","email":"lisi@example.com"}
# {"name":"王五","email":"wangwu@example.com"}
# {"name":"赵六","email":"zhaoliu@example.com"}
# {"name":"钱七","email":"qianqi@example.com"}

### 删除 ID 为 1 的用户
DELETE http://localhost:8080/users/1